---
title: Preparing documentation data
---

## Dataset 1

Sources:
- https://songdongyuan1994.github.io/scDesign3/docs/articles/scDesign3-introduction-vignette.html
- https://scvelo.readthedocs.io/en/stable/vignettes/Pancreas.html#Endocrine-Pancreas
- https://figshare.com/ndownloader/files/40581992

```{r}
library(zellkonverter)
dataset <- readRDS("data/PANCREAS_sce.rds")
writeH5AD(dataset, "data/bastidas_ponce_etal.h5ad")
```

## Dataset 2

Sources:
- https://songdongyuan1994.github.io/ClusterDE/articles/ClusterDE-PBMC.html
- https://figshare.com/ndownloader/files/41486283

```{r}
library(Seurat)
dataset <- readRDS("data/pbmc.rds")
dataset <- as.SingleCellExperiment(dataset)
writeH5AD(dataset, "data/pbmc3k_10x.h5ad")
```

## Dataset 7

```{r}
library(SingleCellExperiment)
library(zellkonverter)
library(ExperimentHub)

eh <- ExperimentHub()
atac_data <- eh[["EH4546"]]
sce <- SingleCellExperiment(assays = list(counts = atac_data))
writeH5AD(sce, "atac_data.h5ad")
```

### Dataset 8

Download directly from:

https://github.com/GreenleafLab/MPAL-Single-Cell-2019?tab=readme-ov-file

## Dataset 9

```{r}
library(Seurat)
library(SeuratData)

InstallData(ds = "thp1.eccite")
eccite <- LoadData(ds = "thp1.eccite")
eccite <- as.SingleCellExperiment(eccite)
writeH5AD(eccite, "eccite.h5ad")
```

## Dataset 10

The accession is here:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM8310950

Let's download all the supplementary files. The glm_ids.txt file is saved on our
data drive.

```{shell}
while read gsm; do
  prefix=${gsm:0:7}nnn
  url="ftp://ftp.ncbi.nlm.nih.gov/geo/samples/${prefix}/${gsm}/suppl/"

  echo "Downloading $gsm"
  wget -r -nH --cut-dirs=8 -np -R "index.html*" "$url"
done < gsm_ids.txt
```
